import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
    await knex.schema.alterTable('users', (table) => {
        table.integer('org_id').nullable();
        table.string('organization').nullable();
        table.string('phone_number').nullable();
        table.string('phone_number_hash').nullable();
        table.string('bvn').nullable();
        table.string('bvn_phone_number').nullable();
        table.date('date_of_birth').nullable();
        table.integer('age').nullable();
        table.string('gender').nullable();
        table.integer('stage_id').nullable();
        table.string('stage').nullable();
        table.string('photo_url').nullable();
        table.string('mifos_client_id').nullable();
        table.string('client_id').nullable();
        table.string('savings_id').nullable();
        table.string('account_number').nullable();
        table.decimal('account_balance', 14, 2).defaultTo(0);
        table.string('account_name').nullable();
        table.string('referral_code').nullable();
        table.string('referred_by').nullable();
        table.string('referrer_name').nullable();
        table.string('referrer_email').nullable();
        table.string('referrer_phone').nullable();
        table.string('referrer_code').nullable();
        table.string('device_id').nullable();
        table.string('notification_token').nullable();
        table.string('device_type').nullable();
        table.integer('tier_id').nullable();
        table.string('tier').nullable();
        table.decimal('withdrawal_limit', 14, 2).nullable();
        table.decimal('deposit_limit', 14, 2).nullable();
        table.decimal('borrower_max_cumulative_amount', 14, 2).nullable();
        table.string('support_email').nullable();
        table.integer('loan_count').nullable().defaultTo(0);
        table.integer('savings_plans').nullable().defaultTo(0);
        table.decimal('savings_target', 14, 2).nullable().defaultTo(0);
        table.decimal('savings_balance', 14, 2).nullable().defaultTo(0);
        table.boolean('activated').defaultTo(false);
        table.timestamp('activated_on').nullable();
        table.boolean('blacklisted').defaultTo(false);
        table.string('reason').nullable();
        table.string('selfie_bvn_check').nullable();
        table.string('selfie_id_check').nullable();
        table.timestamp('last_login_date').nullable();
        table.timestamp('created_on').defaultTo(knex.fn.now());
        table.timestamp('modified_on').nullable().defaultTo(knex.fn.now());
        table.timestamp('deleted_on').nullable();
        table.string('nok_first_name').nullable();
        table.string('nok_last_name').nullable();
        table.string('nok_phone_number').nullable();
        table.string('nok_email').nullable();
        table.string('nok_address').nullable();
        table.string('nok_relationship').nullable();
        table.string('marital_status').nullable();
        table.integer('no_of_dependent').nullable();
        table.string('type_of_residence').nullable();
        table.string('educational_attainment').nullable();
        table.string('employment_status').nullable();
        table.string('sector_of_employment').nullable();
        table.string('current_employer').nullable();
        table.string('employment_category').nullable();
        table.string('monthly_net_income').nullable();
        table.timestamp('work_start_date').nullable();
        table.string('work_email').nullable();
        table.string('country').nullable();
        table.string('city').nullable();
        table.string('lga').nullable();
        table.string('street').nullable();
        table.string('nearest_landmark').nullable();
        table.decimal('longitude', 10, 7).nullable();
        table.decimal('latitude', 10, 7).nullable();
        table.string('address').nullable();
        table.timestamp('process_time').nullable();
    });
}

export async function down(knex: Knex): Promise<void> {
    await knex.schema.alterTable('users', (table) => {
        table.dropColumn('org_id');
        table.dropColumn('organization');
        table.dropColumn('phone_number');
        table.dropColumn('phone_number_hash');
        table.dropColumn('bvn');
        table.dropColumn('bvn_phone_number');
        table.dropColumn('date_of_birth');
        table.dropColumn('age');
        table.dropColumn('gender');
        table.dropColumn('stage_id');
        table.dropColumn('stage');
        table.dropColumn('photo_url');
        table.dropColumn('mifos_client_id');
        table.dropColumn('client_id');
        table.dropColumn('savings_id');
        table.dropColumn('account_number');
        table.dropColumn('account_balance');
        table.dropColumn('account_name');
        table.dropColumn('referral_code');
        table.dropColumn('referred_by');
        table.dropColumn('referrer_name');
        table.dropColumn('referrer_email');
        table.dropColumn('referrer_phone');
        table.dropColumn('referrer_code');
        table.dropColumn('device_id');
        table.dropColumn('notification_token');
        table.dropColumn('device_type');
        table.dropColumn('tier_id');
        table.dropColumn('tier');
        table.dropColumn('withdrawal_limit');
        table.dropColumn('deposit_limit');
        table.dropColumn('borrower_max_cumulative_amount');
        table.dropColumn('support_email');
        table.dropColumn('loan_count');
        table.dropColumn('savings_plans');
        table.dropColumn('savings_target');
        table.dropColumn('savings_balance');
        table.dropColumn('activated');
        table.dropColumn('activated_on');
        table.dropColumn('blacklisted');
        table.dropColumn('reason');
        table.dropColumn('selfie_bvn_check');
        table.dropColumn('selfie_id_check');
        table.dropColumn('last_login_date');
        table.dropColumn('created_on');
        table.dropColumn('modified_on');
        table.dropColumn('deleted_on');
        table.dropColumn('nok_first_name');
        table.dropColumn('nok_last_name');
        table.dropColumn('nok_phone_number');
        table.dropColumn('nok_email');
        table.dropColumn('nok_address');
        table.dropColumn('nok_relationship');
        table.dropColumn('marital_status');
        table.dropColumn('no_of_dependent');
        table.dropColumn('type_of_residence');
        table.dropColumn('educational_attainment');
        table.dropColumn('employment_status');
        table.dropColumn('sector_of_employment');
        table.dropColumn('current_employer');
        table.dropColumn('employment_category');
        table.dropColumn('monthly_net_income');
        table.dropColumn('work_start_date');
        table.dropColumn('work_email');
        table.dropColumn('country');
        table.dropColumn('city');
        table.dropColumn('lga');
        table.dropColumn('street');
        table.dropColumn('nearest_landmark');
        table.dropColumn('longitude');
        table.dropColumn('latitude');
        table.dropColumn('address');
        table.dropColumn('process_time');
    });
}