// src/db/seeds/{timestamp}_seed_users.ts
import { Knex } from 'knex';

export const seed = async (knex: Knex): Promise<void> => {
  // Deletes ALL existing entries
  await knex('users').del();

  // Inserts seed entries
  await knex('users').insert([
    { name: 'Alice', email: 'alice@example.com' },
    { name: 'Bob', email: 'bob@example.com' },
    {
      org_id: 9999,
      organization: 'Example Lender',
      id: 44691,  // This is the user ID if it's the primary key; otherwise, remove if auto-incremented
      name: 'Ado John Sule',
      phone_number: '07062569817',
      phone_number_hash: '318c88a8e1fcfc049114e69128275b4d',
      email: 'Ado@lendsqr.com',
      bvn: '21234567890',
      bvn_phone_number: '08012345678',
      date_of_birth: '1990-09-10',
      age: 26,
      gender: 'Female',
      stage_id: 6,
      stage: 'done',
      photo_url: 'https://image.url.com',
      mifos_client_id: '41053',
      client_id: '41053',
      savings_id: '47197',
      account_number: 'IDR000047197----------',
      account_balance: 1144.25,
      account_name: 'Ado John Sule',
      referral_code: 'B7YEHI',
      referred_by: null,
      referrer_name: null,
      referrer_email: null,
      referrer_phone: null,
      referrer_code: null,
      device_id: 'bd96e5e050c0529d',
      notification_token: '********************************',
      device_type: 'Android',
      tier_id: 24,
      tier: 'Tier 3',
      withdrawal_limit: 1000000,
      deposit_limit: 20000,
      borrower_max_cumulative_amount: 999999999999,
      support_email: 'support@example.com',
      loan_count: 14,
      savings_plans: 0,
      savings_target: 0,
      savings_balance: 0,
      activated: 1,
      activated_on: '2021-02-01T10:15:08.000Z',
      blacklisted: 0,
      reason: null,
      selfie_bvn_check: 'Successful',
      selfie_id_check: 'Successful',
      last_login_date: '2023-10-02T23:20:36.000Z',
      created_on: '2021-02-01T11:02:00.000Z',
      modified_on: '2023-10-02T23:20:36.000Z',
      deleted_on: null,
      nok_first_name: 'Evelyn',
      nok_last_name: 'Peters',
      nok_phone_number: '09099494342',
      nok_email: 'evelyn@lendsqr.com',
      nok_address: 'Ayodele Oke-Owo Street  Gbagada',
      nok_relationship: 'Others',
      marital_status: 'Single',
      no_of_dependent: 0,
      type_of_residence: 'Parents Apartment',
      educational_attainment: 'BSc, HND and Other Equivalent',
      employment_status: 'Employed',
      sector_of_employment: 'Other Financial',
      current_employer: 'Lendsqr',
      employment_category: 'Private Company',
      monthly_net_income: '200,000 - 399,999',
      work_start_date: '2020-11-15T23:00:00.000Z',
      work_email: 'ado@example.com',
      country: 'NGA',
      city: 'Gbagada',
      lga: 'Kosofe',
      street: null,
      nearest_landmark: 'Deeper Life Church',
      longitude: -102.0837554932,
      latitude: 47.421546936,
      address: 'Lagos',
      process_time: '2024-02-28T03:20:26.000Z'
  }
  ]);
};